# Generated by Django 5.0.6 on 2024-05-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
